### ISSUE TITLE
Message history restrict option doesn't work for both platforms

### ISSUE THREAD

**Issue by drewzh** [johnbeadle/CordovaMessagingSDKSample#78]
This hasn't worked since the first SDK we tested. Tested with the latest SDK (2.5.0) on Android and this still isn't having any effect.

Android:
```xml
<integer name='idp_num_history_conversation'>2</integer>
```

iOS
```c
maxPreviousConversationToPresent = 2;
```

**Comment by johnbeadle** [comment]
@drewzh 

```swift
let configurations = LPConfig.defaultConfiguration
configurations.maxPreviousConversationToPresent = 1
```

Works as expected. **This will set the number of resolved/closed conversations to be shown on opening the conversation screen**.

See below GIF. 

* The setting = 1
* Conversation screens 1 resolved conversation
* User scrolls up and refreshes via the pull down gesture and 3 other resolved conversations are then downloaded.

![ios max resolved conv 1](https://user-images.githubusercontent.com/10999907/28114788-39d8724a-66fa-11e7-80a5-f07bda8035e0.gif)

**Comment by drewzh** [comment]
Thanks for testing this John. This may have been fixed recently with iOS perhaps, but we're unable to test as we've got an outstanding issue with switching to 2.5.0 https://github.com/johnbeadle/CordovaMessagingSDKSample/issues/74.

Can you confirm that you're able to restrict the message history on Android?

I've just double checked both platforms and the configuration seems to be correctly set, but on Android 2.5.0 at least, this is still showing all history.

**Comment by johnbeadle** [comment]
@drewzh  Seemingly still not working in 2.5.0.8 as the below shows - loads more than the set 2 limit resolved conversations...


![giphy 2](https://user-images.githubusercontent.com/10999907/28140258-87167a0c-674f-11e7-90a7-a3958d6925ca.gif)

Also shows URL Preview issue not fixed in Android 2.5.0.8 as well #77

**Comment by drewzh** [comment]
Verified that this works correctly in iOS.
